name: Call TFCheck and TFDocs

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "**/*.tf"
      - ".github/workflows/*.yml"
  push:
    branches:
      - main
    paths:
      - "**/*.tf"
      - ".github/workflows/*.yml"

permissions:
  contents: write

jobs:
  call-tfcheck:
    uses: ./.github/workflows/tflint-and-checks.yml
    with:
      working-directory: "${GITHUB_WORKSPACE}"
      tflint-version: "latest"
      enable-terraform-format-check: true
      enable-terraform-lint-check: false # Set to true to enable TFLint check
      enable-gha-lint-check: false # Set to true to enable GHA Lint check

  call-tfdocs:
    if: github.event_name == 'pull_request' && github.head_ref != 'develop'
    needs: call-tfcheck
    uses: ./.github/workflows/tfdocs.yml
    with:
      working-directory: "."
      pr-ref: ${{ github.event.pull_request.head.ref }}
